### ISSUE TITLE
library endpoint Not Found

### ISSUE THREAD

**Issue by crypticviper** [tenekev/immich-offline-files-remover#1]
Hello,

Thanks for your effort on this script/docker. I tried to use it and I get several immich API endpoint related issues. Looks like "/api/library" doesn't exist anymore and it replaced by "/api/libraries". Even the JSON returned by the libraries API seems to be different than what the script is expecting.

I tried to fix the scripts but at some point I gave up because it was beyond my Python skills.

I ended up using below script instead:

https://github.com/Thoroslives/immich_remove_offline_files

Cheers
~v

**Comment by tenekev** [comment]
Hey there! I'm aware of the issue and plan to update it when I have more time. They actually changed the API endpoints and the documentation about it while I was writing this version. It resulted in an hour of troubleshooting and going crazy why things don't work.

**Comment by tenekev** [comment]
Issue should be fixed. I rewrote the script.

**Comment by crypticviper** [comment]
> Issue should be fixed. I rewrote the script.

Cool, thanks! I'll try it out.
